Repository ssg-240304-java2/shop-ssgnack, pull requests merged in 2024-06, with the labels that each got.

#24 재고 관리 기능 개발 완료
  ssgnack/src/main/java/com/ssgnack/inboundStock/controller/InboundStockController.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/dao/InboundStockMapper.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/dto/InboundDTO.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/dto/StockDTO.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockService.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockServiceImpl.java
  ssgnack/src/main/resources/mappers/InboundStock.xml
  ssgnack/src/main/resources/static/css/inboundStock/global_InboundStock.css
  ssgnack/src/main/resources/static/css/inboundStock/inbound.css
  ssgnack/src/main/resources/static/css/inboundStock/stock.css
  ssgnack/src/main/resources/templates/common/fragment/main.html
  ssgnack/src/main/resources/templates/inboundStock/inbound.html
  ssgnack/src/main/resources/templates/inboundStock/package.json
  ssgnack/src/main/resources/templates/inboundStock/public/administration-1@2x.png
  ssgnack/src/main/resources/templates/inboundStock/public/arrowchevrondown.svg
  ssgnack/src/main/resources/templates/inboundStock/public/customerloyalty-1@2x.png
  ssgnack/src/main/resources/templates/inboundStock/public/order-2@2x.png
  ssgnack/src/main/resources/templates/inboundStock/public/productmanagement-1@2x.png
  ssgnack/src/main/resources/templates/inboundStock/public/promotion-1@2x.png
  ssgnack/src/main/resources/templates/inboundStock/public/vector.svg
  ssgnack/src/main/resources/templates/inboundStock/stock.html
Labels: 구성🛠️, 완료✅

#29 #5 feat: Add functionality to create and store inbound data
  ssgnack/src/main/java/com/ssgnack/inboundStock/controller/InboundStockController.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/dao/InboundStockMapper.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockService.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockServiceImpl.java
  ssgnack/src/main/resources/mappers/InboundStock.xml
  ssgnack/src/main/resources/templates/inboundStock/inbound.html
  ssgnack/src/main/resources/templates/inboundStock/stock.html
Labels: 구성🛠️

#31 #7 UI 개선
  ssgnack/src/main/resources/templates/common/fragment/main.html
  ssgnack/src/main/resources/templates/report/brandGraph.html
  ssgnack/src/main/resources/templates/report/monthlyGraph.html
  ssgnack/src/main/resources/templates/report/productGraph.html
Labels: 수정🚧, UI

#33 출고 기능 완료했습니다.
  ssgnack/src/main/java/com/ssgnack/outbound/controller/OutboundController.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/dao/OutboundMapper.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/dto/OutboundDTO.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/service/OutboundService.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/service/OutboundServiceImpl.java
  ssgnack/src/main/resources/mappers/Outbound.xml
  ssgnack/src/main/resources/static/css/outbound/global_outbound.css
  ssgnack/src/main/resources/static/css/outbound/order.css
  ssgnack/src/main/resources/static/css/outbound/outbound.css
  ssgnack/src/main/resources/templates/common/fragment/main.html
  ssgnack/src/main/resources/templates/outbound/order.html
  ssgnack/src/main/resources/templates/outbound/outbound.html
  ssgnack/src/main/resources/templates/outbound/package.json
  ssgnack/src/main/resources/templates/outbound/public/administration-1@2x.png
  ssgnack/src/main/resources/templates/outbound/public/arrowchevrondown.svg
  ssgnack/src/main/resources/templates/outbound/public/customerloyalty-1@2x.png
  ssgnack/src/main/resources/templates/outbound/public/image-1@2x.png
  ssgnack/src/main/resources/templates/outbound/public/img.svg
  ssgnack/src/main/resources/templates/outbound/public/order-2@2x.png
  ssgnack/src/main/resources/templates/outbound/public/productmanagement-1@2x.png
  ssgnack/src/main/resources/templates/outbound/public/promotion-1@2x.png
  ssgnack/src/main/resources/templates/outbound/public/vector.svg
Labels: 구성🛠️, UI

#34 html,기능,페이지 순서 수정
  ssgnack/src/main/java/com/ssgnack/admin/controller/AdminController.java
  ssgnack/src/main/java/com/ssgnack/report/controller/ReportController.java
  ssgnack/src/main/java/com/ssgnack/report/model/service/ReportServiceImpl.java
  ssgnack/src/main/resources/static/css/report/brandGraph.css
  ssgnack/src/main/resources/static/css/report/monthlyGraph.css
  ssgnack/src/main/resources/static/css/report/productGraph.css
  ssgnack/src/main/resources/static/main.css
  ssgnack/src/main/resources/templates/admin/login.html
  ssgnack/src/main/resources/templates/common/fragment/main.html
  ssgnack/src/main/resources/templates/report/brandGraph.html
  ssgnack/src/main/resources/templates/report/monthlyGraph.html
  ssgnack/src/main/resources/templates/report/productGraph.html
Labels: 완료✅

#38 입출고, 재고조회 모든 기능 개발 완료입니다.
  ssgnack/src/main/java/com/ssgnack/outbound/controller/OutboundController.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/dao/OutboundMapper.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/service/OutboundService.java
  ssgnack/src/main/java/com/ssgnack/outbound/model/service/OutboundServiceImpl.java
  ssgnack/src/main/resources/mappers/Outbound.xml
  ssgnack/src/main/resources/static/css/outbound/order.css
  ssgnack/src/main/resources/templates/inboundStock/inbound.html
  ssgnack/src/main/resources/templates/outbound/order.html
  ssgnack/src/main/resources/templates/outbound/outbound.html
Labels: 완료✅

#40 UI 수정
  ssgnack/src/main/resources/static/css/inboundStock/inbound.css
  ssgnack/src/main/resources/static/css/outbound/outbound.css
  ssgnack/src/main/resources/static/css/product/product.css
  ssgnack/src/main/resources/static/main.css
  ssgnack/src/main/resources/templates/common/fragment/main.html
  ssgnack/src/main/resources/templates/inboundStock/inbound.html
  ssgnack/src/main/resources/templates/inboundStock/stock.html
  ssgnack/src/main/resources/templates/outbound/order.html
  ssgnack/src/main/resources/templates/outbound/outbound.html
  ssgnack/src/main/resources/templates/product/delete.html
  ssgnack/src/main/resources/templates/product/insert.html
  ssgnack/src/main/resources/templates/product/main.html
  ssgnack/src/main/resources/templates/product/update.html
  ssgnack/src/main/resources/templates/report/brandGraph.html
  ssgnack/src/main/resources/templates/report/monthlyGraph.html
  ssgnack/src/main/resources/templates/report/productGraph.html
Labels: UI

#41 재고 조회 검색 기능 개발 완료
  ssgnack/src/main/java/com/ssgnack/inboundStock/controller/InboundStockController.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/dao/InboundStockMapper.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockService.java
  ssgnack/src/main/java/com/ssgnack/inboundStock/model/service/InboundStockServiceImpl.java
  ssgnack/src/main/resources/mappers/InboundStock.xml
  ssgnack/src/main/resources/static/css/inboundStock/stock.css
  ssgnack/src/main/resources/static/js/inboundStock/stock.js
  ssgnack/src/main/resources/templates/inboundStock/stock.html
Labels: 완료✅

#44 #16 Modify: Update UI for stock inquiry
  ssgnack/src/main/resources/templates/inboundStock/stock.html
Labels: 수정🚧, UI
